#!/usr/bin/env python3
"""Build brew-log/grinders.js from the CoffeeOS grinder table.

  python3 -I tools/build_grinders.py path/to/grind.js brew-log/grinders.js

grind.js is CoffeeOS (com.coffeeos.app) assets/flutter_assets/assets/data/grind.js.
Its numbers trace back to Honest Coffee Guide's grind size charts.

Model (same as the CoffeeOS chart): every tick in tickValues is one equal step on
the chart, micron = min + (max - min) * index / (ticks - 1), in source order.
Fixes applied here, on top of the raw table:
  - typos in tick labels (Niche Zero "06.5", Varia Evo Hybrid second "0",
    Lido OG "100+20" in the 200 block, J-Max "3.0", Weber KEY "2.10");
  - Bodum Bistro word labels mapped to their dial numbers;
  - KitchenAid lists stay in source order: on those dials 1 is the coarsest,
    so the CoffeeOS app's own reversal of them is wrong.
Repeated labels (Baratza Encore ESP macro steps) are kept as spacing; the app
reads each setting at its first occurrence.
"""
import json
import re
import sys

LABEL_FIXES = {
    # (brand model, index): (expected raw label, fixed label)
    ("Niche Zero", 65): ("06.5", "0.65"),
    ("Varia Evo Hybrid", 72): ("0", "1+0"),
    ("Orphan Espresso Lido OG", 44): ("100+20", "200+20"),
    ("1Zpresso J-Max", 270): ("3.0", "3.0.0"),
    ("1Zpresso J-Max S", 270): ("3.0", "3.0.0"),
    ("Weber Workshops KEY Mk1", 200): ("2.10", "2.10.0"),
}
WORD_LABELS = {"FINE": "1", "MEDIUM": "6", "COARSE": "12"}  # Bodum Bistro 10903

METHODS_AR = {
    "Turkish": "تركي",
    "Espresso": "إسبريسو",
    "V60": "V60",
    "Aeropress": "AeroPress",
    "Moka Pot": "موكا بوت",
    "Pour Over": "تقطير يدوي",
    "Siphon": "سايفون",
    "Filter Coffee Machine": "مكينة تقطير",
    "French Press": "فرنش بريس",
    "Cupping": "كبينق",
    "Cold Brew": "كولد برو",
    "Cold Drip": "كولد دريب",
    "Steep-and-release": "نقع وتصريف",
}


def load(path):
    src = open(path, encoding="utf-8").read()
    i = src.index("const grinders = ") + len("const grinders = ")
    grinders = json.loads(src[i:src.index("];", i) + 1])
    k = src.index("const brewingMethods = ") + len("const brewingMethods = ")
    raw = src[k:src.index("];", k) + 1]
    methods = json.loads(re.sub(r",(\s*})", r"\1", re.sub(r"(\w+):", r'"\1":', raw)))
    return grinders, methods


def ticks_of(name, ticks):
    ticks = [WORD_LABELS.get(t, t) for t in ticks]
    for (n, idx), (want, fixed) in LABEL_FIXES.items():
        if n == name:
            if ticks[idx] != want:
                sys.exit(f"{name}[{idx}] is {ticks[idx]!r}, expected {want!r}; source changed, recheck fixes")
            ticks[idx] = fixed
    return ticks


def encode(ticks):
    # A plain run of integers is stored as [first, last]; anything else as "a|b|c".
    if all(re.fullmatch(r"\d+", t) for t in ticks):
        a = int(ticks[0])
        if [int(t) for t in ticks] == list(range(a, a + len(ticks))) and all(str(int(t)) == t for t in ticks):
            return [a, a + len(ticks) - 1]
    assert not any("|" in t for t in ticks)
    return "|".join(ticks)


def main(src, out):
    grinders, methods = load(src)
    rows = []
    for x in sorted(grinders, key=lambda x: (x["brand"].lower(), x["model"].lower())):
        brand, model = x["brand"].strip(), x["model"].strip()
        name = f"{x['brand']} {x['model']}"
        cs = x["chart_settings"]
        lo, hi = cs["micronRange"]["min"], cs["micronRange"]["max"]
        ticks = ticks_of(name, cs["tickValues"])
        if len(ticks) < 2 or not lo < hi:
            sys.exit(f"bad range for {name}")
        row = {"b": brand, "m": model, "lo": lo, "hi": hi, "t": encode(ticks)}
        zones = [[a["label"] or "", a["min"], a["max"]] for a in cs["secondaryAxis"]]
        if zones:
            row["z"] = zones
        rows.append(row)
    bm = [{"l": METHODS_AR.get(m["label"], m["label"]), "min": m["min"], "max": m["max"]} for m in methods]
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("// Generated by tools/build_grinders.py from the CoffeeOS grinder table"
                 " (Honest Coffee Guide charts). Do not edit by hand.\n")
        fh.write("var GRINDERS=" + json.dumps(rows, ensure_ascii=False, separators=(",", ":")) + ";\n")
        fh.write("var BREW_METHODS=" + json.dumps(bm, ensure_ascii=False, separators=(",", ":")) + ";\n")
    print(f"{len(rows)} grinders -> {out}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
